import java.util.Objects;

/**
 * A class representing a prioritized token
 */
public class Token
{
	private final String tokenID;
	private final int priority;

	public Token(String tokenID, int priority)
	{
		this.tokenID = tokenID;
		this.priority = priority;
	}

	/**
	 *
	 * Get the unique identifier for this token (guaranteed to be unique across all tokens).
	 * @return the token ID
	 */
	public String getTokenID()
	{
		return tokenID;
	}

	/**
	 * Get the priority. A lower integer number indicates a higher priority.
	 * @return the priority
	 */
	public int getPriority()
	{
		return priority;
	}

	// Equals and Hashcode autogenerated.
	@Override
	public boolean equals(Object o) {
		if (this == o) return true;
		if (o == null || getClass() != o.getClass()) return false;
		Token token = (Token) o;
		return priority == token.priority &&
				Objects.equals(tokenID, token.tokenID);
	}

	@Override
	public int hashCode() {

		return Objects.hash(tokenID, priority);
	}
}

